export const COMMAND_PRESETS = {
  'ls -la': {
    name: 'ls -la',
    title: 'Directory Listing & Inode Metadata',
    summaryText: 'How Linux lists files: Terminal ➔ Shell finds /bin/ls ➔ Clones process (fork) ➔ Kernel reads directory metadata from disk ➔ Streams text back.',
    stages: [
      {
        id: 'input_pty',
        stepNum: 1,
        timeOffset: 0,
        name: '1. You Type "ls -la" on Keyboard',
        simpleTitle: '1. Capturing Keystrokes',
        layer: 'User Space',
        activeNode: 'terminal',
        route: null,
        sound: 'key',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: null,
        registers: { RIP: '0x7fff4010', RAX: '0x00000000', RSP: '0x7ffeef80', RDI: '0x0' },
        simpleExplanation: 'When you press Enter, your terminal app (like GNOME Terminal, Alacritty, or VS Code) captures the raw characters "ls -la\\n" and sends them to the pseudo-terminal device (/dev/ptmx).',
        explanation: 'Keystrokes "ls -la\\n" are sent through the display server to the Terminal Emulator, which writes them into the Pseudoterminal Master (/dev/ptmx).',
        analogy: '💡 Analogy: You write an order on a notepad at a restaurant and hand it to the waiter.',
        codeSnippet: `write(master_ptmx_fd, "ls -la\\n", 7);`,
        terminalOutput: `user@linux:~$ ls -la`
      },
      {
        id: 'shell_parse',
        stepNum: 2,
        timeOffset: 600,
        name: '2. Shell Splits & Understands Command',
        simpleTitle: '2. Shell Tokenizing & Syntax',
        layer: 'User Space (Bash)',
        activeNode: 'lexer',
        route: { from: 'terminal', to: 'lexer', color: 0x00f3ff },
        sound: 'key',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: null,
        registers: { RIP: '0x5555556a', RAX: '0x00000002', RSP: '0x7ffeef20', RDI: 'argv[0]="ls"' },
        simpleExplanation: 'The Shell (Bash/Zsh) breaks the text into two parts: program name ("ls") and flags ("-la"). It checks if you have any aliases or variables like $HOME.',
        explanation: 'Bash lexes the string into tokens ["ls", "-la"], checks for shell aliases, and builds the command AST node.',
        analogy: '💡 Analogy: The waiter reads your order: "ls" (the dish) with "-la" (extra options).',
        codeSnippet: `COMMAND *cmd = parse_string("ls -la");\n// cmd->type = CMD_SIMPLE, cmd->args = ["ls", "-la", NULL]`,
        terminalOutput: null
      },
      {
        id: 'path_lookup',
        stepNum: 3,
        timeOffset: 1300,
        name: '3. Shell Finds the Program on Disk ($PATH)',
        simpleTitle: '3. Searching $PATH Folders',
        layer: 'User Space (Shell)',
        activeNode: 'path',
        route: { from: 'lexer', to: 'path', color: 0x00f3ff },
        sound: 'key',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: 'faccessat2()',
        registers: { RIP: '0x55555580', RAX: '0x00000106', RSP: '0x7ffeef00', RDI: '"/usr/bin/ls"' },
        simpleExplanation: 'The shell does not know how to list files itself. It searches folders in your $PATH variable and discovers the compiled program located at /usr/bin/ls.',
        explanation: 'Shell checks if "ls" is a builtin (no). It traverses $PATH and locates the ELF executable at /usr/bin/ls.',
        analogy: '💡 Analogy: Looking up the recipe book in the kitchen cabinet (/usr/bin/ls).',
        codeSnippet: `if (faccessat2(AT_FDCWD, "/usr/bin/ls", X_OK, 0) == 0) {\n  target_binary = "/usr/bin/ls";\n}`,
        terminalOutput: null
      },
      {
        id: 'fork_child',
        stepNum: 4,
        timeOffset: 2000,
        name: '4. fork() Clones a Child Process (PID 4129)',
        simpleTitle: '4. Process Cloning (fork)',
        layer: 'Syscall Gateway (Kernel)',
        activeNode: 'fork',
        route: { from: 'path', to: 'fork', color: 0xff0077 },
        sound: 'fork',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'clone3() / fork() [57]',
        registers: { RIP: '0x7fff4055', RAX: '4129 (New PID)', RSP: '0x7ffeef00', RDI: 'SIGCHLD' },
        simpleExplanation: 'CRITICAL STEP: If the shell executed "ls" directly, the shell itself would end! So it asks the Linux Kernel to clone an identical child worker process with its own PID (e.g. 4129).',
        explanation: 'Bash calls fork() to create a child process. The kernel duplicates the task_struct, allocates PID 4129 with Copy-On-Write (COW) memory.',
        analogy: '💡 Analogy: The head chef hires an assistant worker to cook this specific meal so the head chef can keep taking orders.',
        codeSnippet: `pid_t pid = fork();\nif (pid == 0) {\n  /* Child Process (PID 4129) */\n  execve("/usr/bin/ls", argv, envp);\n}`,
        terminalOutput: null
      },
      {
        id: 'sys_execve',
        stepNum: 5,
        timeOffset: 2800,
        name: '5. execve() Replaces Child Brain with "ls"',
        simpleTitle: '5. Transform Process (execve)',
        layer: 'Syscall Gateway',
        activeNode: 'syscall_dispatcher',
        route: { from: 'fork', to: 'syscall', color: 0xff0077 },
        sound: 'syscall',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'execve(59)',
        registers: { RIP: '0xffffffff8100', RAX: '59', RSP: '0xffffc90000', RDI: '0x7fff4080' },
        simpleExplanation: 'The child process calls execve("/usr/bin/ls"). CPU switches from User Mode (Ring 3) to Kernel Mode (Ring 0). The kernel wipes the child memory and replaces it with the "ls" machine code.',
        explanation: 'Child process executes `syscall` instruction with RAX=59. CPU switches hardware privilege level to Ring 0 (Kernel).',
        analogy: '💡 Analogy: The assistant worker clears their desk and opens the exact manual for cooking dish #59.',
        codeSnippet: `mov rax, 59       ; __NR_execve\nmov rdi, path_ptr ; "/usr/bin/ls"\nsyscall          ; Switch to Ring 0`,
        terminalOutput: null
      },
      {
        id: 'elf_mmu_load',
        stepNum: 6,
        timeOffset: 3600,
        name: '6. MMU Sets Up Memory (Code, Data, Stack)',
        simpleTitle: '6. Virtual Memory Mapping (MMU)',
        layer: 'Kernel & MMU',
        activeNode: 'mmu_memory',
        route: { from: 'syscall', to: 'mmu', color: 0x2979ff },
        sound: 'kernel',
        cameraTarget: 'kernel',
        ring: 0,
        syscall: 'mmap() [9]',
        registers: { CR3: '0x1a820000', RIP: '0x7ffff7fd', RSP: '0x7fffffffe0', RAX: '0x0' },
        simpleExplanation: 'The Memory Management Unit maps virtual memory: .text (executable code), .data (variables), and Stack (command arguments "-la"). Dynamic libraries (libc.so) are loaded.',
        explanation: 'Kernel parses the ELF header of /usr/bin/ls, clears previous address space, maps .text (RX), .rodata (R), .data (RW), Stack and Heap, and loads ld-linux dynamic linker.',
        analogy: '💡 Analogy: Setting up the workstation with all needed cutting boards and ingredients in dedicated zones.',
        codeSnippet: `load_elf_binary(bprm);\nsetup_arg_pages(bprm, randomize_va_space);\ncreate_elf_tables(bprm);`,
        terminalOutput: null
      },
      {
        id: 'vfs_getdents',
        stepNum: 7,
        timeOffset: 4500,
        name: '7. Kernel Reads Directory Inodes (getdents64)',
        simpleTitle: '7. Reading Directory Metadata',
        layer: 'VFS & Storage',
        activeNode: 'vfs_tree',
        route: { from: 'mmu', to: 'vfs', color: 0x00ff88 },
        sound: 'disk',
        cameraTarget: 'vfs',
        ring: 0,
        syscall: 'getdents64() [217]',
        registers: { RIP: '0x7ffff7e2', RAX: '217', RDI: '3 (dir_fd)', RSI: '0x55555578' },
        simpleExplanation: '`ls` asks the kernel for directory entries. The Virtual File System (VFS) reads the directory inode from the ext4 filesystem to fetch filenames, file sizes, permissions (rwxr-xr-x), and timestamps.',
        explanation: '`ls` opens current working directory (`openat`) and reads directory entry records (inodes, filenames, file types) via `getdents64()`.',
        analogy: '💡 Analogy: Opening the storage room cabinet index to see what items are on the shelves.',
        codeSnippet: `int fd = openat(AT_FDCWD, ".", O_RDONLY|O_DIRECTORY);\nstruct linux_dirent64 *d = malloc(buf_size);\nsyscall(SYS_getdents64, fd, d, buf_size);`,
        terminalOutput: null
      },
      {
        id: 'output_render',
        stepNum: 8,
        timeOffset: 5400,
        name: '8. Stream Formatted Text to Terminal & Exit',
        simpleTitle: '8. Output Rendered & Shell Returns',
        layer: 'User Space & Terminal',
        activeNode: 'terminal',
        route: { from: 'vfs', to: 'terminal', color: 0x00f3ff },
        sound: 'success',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: 'write(1) & exit_group(0)',
        registers: { RIP: '0x7ffff7d0', RAX: '0 (exit code)', RSP: '0x7fffffffd0', RDI: '0' },
        simpleExplanation: '`ls` formats the text with colors/columns, writes it to File Descriptor 1 (stdout). The child exits with code 0. Parent shell reaps the child and shows your prompt again!',
        explanation: '`ls` writes formatted directory listing bytes to file descriptor 1 (stdout), then calls `exit_group(0)`. Kernel reaps process and returns shell prompt.',
        analogy: '💡 Analogy: The assistant places the prepared meal on the serving counter and punches out. The head chef is ready for your next order.',
        codeSnippet: `write(STDOUT_FILENO, output_str, len);\nexit_group(0);`,
        terminalOutput: `total 32
drwxr-xr-x  5 user user 4096 Aug 28 12:50 .
drwxr-xr-x 23 user user 4096 Aug 28 12:48 ..
-rw-r--r--  1 user user  320 Aug 28 12:51 package.json
drwxr-xr-x  6 user user 4096 Aug 28 12:52 src
drwxr-xr-x 48 user user 4096 Aug 28 12:51 node_modules
-rw-r--r--  1 user user  180 Aug 28 12:52 vite.config.js
user@linux:~$ `
      }
    ]
  },

  'cat file.txt': {
    name: 'cat file.txt',
    title: 'File Reading & RAM Page Cache Flow',
    summaryText: 'How Linux reads a file: Checks if data is already cached in RAM Page Cache. If not, requests hardware DMA disk read, then streams bytes.',
    stages: [
      {
        id: 'cat_input',
        stepNum: 1,
        timeOffset: 0,
        name: '1. You Request "cat file.txt"',
        simpleTitle: '1. Shell Starts Process',
        layer: 'User Space',
        activeNode: 'terminal',
        route: null,
        sound: 'key',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: null,
        registers: { RIP: '0x55555550', RAX: '0', RSP: '0x7ffeef00', RDI: '"cat"' },
        simpleExplanation: 'Shell parses command and forks /usr/bin/cat with argument "file.txt".',
        explanation: 'Shell reads "cat file.txt", validates binary location at /usr/bin/cat.',
        analogy: '💡 Analogy: Asking a library assistant to fetch a specific book from the archives.',
        codeSnippet: `execve("/usr/bin/cat", ["cat", "file.txt"], envp);`,
        terminalOutput: `user@linux:~$ cat file.txt`
      },
      {
        id: 'cat_openat',
        stepNum: 2,
        timeOffset: 800,
        name: '2. openat() Asks Kernel for File Handle',
        simpleTitle: '2. Kernel Looks up Inode',
        layer: 'VFS Layer',
        activeNode: 'vfs_tree',
        route: { from: 'terminal', to: 'vfs', color: 0x00ff88 },
        sound: 'syscall',
        cameraTarget: 'vfs',
        ring: 0,
        syscall: 'openat(257)',
        registers: { RAX: '257', RDI: 'AT_FDCWD', RSI: '"file.txt"', RDX: 'O_RDONLY' },
        simpleExplanation: '`cat` calls openat(). The kernel verifies file permissions and assigns integer File Descriptor 3 to represent this open file.',
        explanation: 'Kernel traverses directory entries to find "file.txt", retrieving its ext4 inode #94821 and file permissions.',
        analogy: '💡 Analogy: The librarian verifies your library card and gives you a claim ticket (fd 3).',
        codeSnippet: `int fd = openat(AT_FDCWD, "file.txt", O_RDONLY); // Returns fd 3`,
        terminalOutput: null
      },
      {
        id: 'cat_pagecache',
        stepNum: 3,
        timeOffset: 1700,
        name: '3. Check Kernel RAM Page Cache',
        simpleTitle: '3. RAM Cache Check (Speed Booster)',
        layer: 'Kernel Page Cache',
        activeNode: 'page_cache',
        route: { from: 'vfs', to: 'page_cache', color: 0x00ff88 },
        sound: 'kernel',
        cameraTarget: 'vfs',
        ring: 0,
        syscall: 'find_get_page()',
        registers: { RIP: '0xffffffff8124', RAX: '0x0 (Cache Miss)', RSP: '0xffffc900' },
        simpleExplanation: 'Before touching the slow physical SSD/Hard drive, the kernel checks if the file pages are already sitting in RAM (Page Cache). If it is a Cache Hit, it skips disk I/O entirely!',
        explanation: 'Kernel checks if file 4KB pages reside in RAM. On Cache Miss, it dispatches a Block I/O request to hardware storage.',
        analogy: '💡 Analogy: Checking if the book is already resting on the quick-access reading table.',
        codeSnippet: `struct page *page = find_get_page(mapping, index);\nif (!page) {\n  page_cache_sync_readahead(...);\n}`,
        terminalOutput: null
      },
      {
        id: 'cat_disk_dma',
        stepNum: 4,
        timeOffset: 2700,
        name: '4. Physical Storage DMA Transfer',
        simpleTitle: '4. SSD/Disk Hardware Transfer',
        layer: 'Hardware Storage',
        activeNode: 'disk',
        route: { from: 'page_cache', to: 'disk', color: 0x00ff88 },
        sound: 'disk',
        cameraTarget: 'vfs',
        ring: 0,
        syscall: 'submit_bio()',
        registers: { RIP: '0xffffffff8180', RAX: '0x0', RDI: 'struct bio*' },
        simpleExplanation: 'On a Cache Miss, the storage controller reads the magnetic/flash sectors from disk and copies them straight into RAM via Direct Memory Access (DMA).',
        explanation: 'Storage controller transfers raw disk sectors directly into physical RAM buffers via Direct Memory Access (DMA).',
        analogy: '💡 Analogy: Walking to the deep underground archive vault to bring the physical book to the front desk.',
        codeSnippet: `submit_bio(&bio);\n// Hardware interrupt signals DMA completion`,
        terminalOutput: null
      },
      {
        id: 'cat_stdout',
        stepNum: 5,
        timeOffset: 3700,
        name: '5. read() & write(1) File Text to Screen',
        simpleTitle: '5. Displaying File Contents',
        layer: 'User Space & Terminal',
        activeNode: 'terminal',
        route: { from: 'disk', to: 'terminal', color: 0x00f3ff },
        sound: 'success',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: 'read(3) & write(1)',
        registers: { RAX: '1 (sys_write)', RDI: '1 (stdout)', RSI: '0x55555560', RDX: '64' },
        simpleExplanation: '`cat` reads the bytes from the RAM buffer and writes them to stdout (1). The terminal window displays the text.',
        explanation: 'cat copies bytes from page cache into user buffer, writes to stdout descriptor 1, and the terminal displays the file contents.',
        analogy: '💡 Analogy: Handing the book pages to the reader.',
        codeSnippet: `read(fd, buffer, 4096);\nwrite(STDOUT_FILENO, buffer, bytes_read);`,
        terminalOutput: `[SYSTEM LOG - Linux Kernel 6.11]
Status: System operational.
Memory: 4-Level Paging active.
Virtual File System: ext4 mounted on / (rw)
user@linux:~$ `
      }
    ]
  },

  'grep "WARN" log | wc -l': {
    name: 'grep "WARN" log | wc -l',
    title: 'Unix Pipelines & Inter-Process Communication',
    summaryText: 'How pipelines work: pipe() creates a shared RAM buffer. Two programs run concurrently, one pushing output into the pipe, the other reading it live.',
    stages: [
      {
        id: 'pipe_create',
        stepNum: 1,
        timeOffset: 0,
        name: '1. pipe() Allocates Shared RAM Ring Buffer',
        simpleTitle: '1. Creating Kernel Pipe in RAM',
        layer: 'Syscall & FD Table',
        activeNode: 'fd_table',
        route: null,
        sound: 'syscall',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'pipe2([3, 4], O_CLOEXEC)',
        registers: { RAX: '293 (sys_pipe2)', RDI: 'pipefd[2]' },
        simpleExplanation: 'The shell sees the pipe "|" character and asks the kernel to create a circular 64KB RAM buffer with two file descriptors: read end (fd 3) and write end (fd 4).',
        explanation: 'Shell calls pipe2() to create a unidirectional kernel FIFO ring buffer in RAM with read fd[3] and write fd[4].',
        analogy: '💡 Analogy: Building a conveyor belt between two worker stations.',
        codeSnippet: `int p[2];\npipe(p); // p[0] = 3 (read end), p[1] = 4 (write end)`,
        terminalOutput: `user@linux:~$ grep "WARN" log | wc -l`
      },
      {
        id: 'pipe_fork_both',
        stepNum: 2,
        timeOffset: 900,
        name: '2. Shell Forks Two Child Workers Concurrently',
        simpleTitle: '2. Dual Fork (grep & wc)',
        layer: 'Kernel Process Factory',
        activeNode: 'fork',
        route: { from: 'fd_table', to: 'fork', color: 0xff0077 },
        sound: 'fork',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'fork() x2',
        registers: { PID_A: '5120 (grep)', PID_B: '5121 (wc)' },
        simpleExplanation: 'Shell spawns two separate child processes: PID A will run "grep", PID B will run "wc". Both run at the same time!',
        explanation: 'Shell forks two child processes concurrently to run both sides of the pipeline.',
        analogy: '💡 Analogy: Hiring Worker A (filterer) and Worker B (counter) to work simultaneously.',
        codeSnippet: `pid_t pid1 = fork(); // grep process\npid_t pid2 = fork(); // wc process`,
        terminalOutput: null
      },
      {
        id: 'pipe_dup2',
        stepNum: 3,
        timeOffset: 1800,
        name: '3. dup2() Connects Outputs & Inputs',
        simpleTitle: '3. Plumbing the Data Pipe (dup2)',
        layer: 'Syscall Gateway',
        activeNode: 'fd_table',
        route: { from: 'fork', to: 'fd_table', color: 0xff0077 },
        sound: 'syscall',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'dup2(4, 1) & dup2(3, 0)',
        registers: { RAX: '33 (sys_dup2)', RDI: '4', RSI: '1' },
        simpleExplanation: '`dup2()` redirects grep\'s stdout (1) into the pipe\'s write end, and redirects wc\'s stdin (0) to read from the pipe\'s read end. Neither program knows a pipe exists—they just read and write normally!',
        explanation: 'Child 1 duplicates write pipe end to stdout (1). Child 2 duplicates read pipe end to stdin (0). Unused pipe ends are closed.',
        analogy: '💡 Analogy: Snapping the conveyor belt outlet directly into Worker B\'s input bin.',
        codeSnippet: `// Child 1 (grep):\ndup2(p[1], STDOUT_FILENO); close(p[0]);\n// Child 2 (wc):\ndup2(p[0], STDIN_FILENO); close(p[1]);`,
        terminalOutput: null
      },
      {
        id: 'pipe_streaming',
        stepNum: 4,
        timeOffset: 2800,
        name: '4. Kernel CPU Scheduler Streams Data in RAM',
        simpleTitle: '4. Live Stream in RAM (Zero Disk IO)',
        layer: 'Kernel CPU & Scheduler',
        activeNode: 'scheduler',
        route: { from: 'fd_table', to: 'cpu', color: 0xffaa00 },
        sound: 'kernel',
        cameraTarget: 'kernel',
        ring: 0,
        syscall: 'splice() / pipe_write()',
        registers: { RIP: '0xffffffff8130', RAX: '0', CFS_VTIME: '124040' },
        simpleExplanation: '`grep` pushes matching lines into the kernel RAM buffer. As lines arrive, the CPU wakes up `wc` to read and count them. Zero disk storage is used!',
        explanation: '`grep` writes matched lines into kernel pipe buffer. If buffer is full, grep sleeps and scheduler yields CPU to `wc` to read from stdin.',
        analogy: '💡 Analogy: Worker A puts matched items on the conveyor belt, Worker B counts them instantly.',
        codeSnippet: `pipe_write(struct kiocb *iocb, struct iov_iter *from);\npipe_read(struct kiocb *iocb, struct iov_iter *to);`,
        terminalOutput: null
      },
      {
        id: 'pipe_complete',
        stepNum: 5,
        timeOffset: 3800,
        name: '5. wc Outputs Final Count (42)',
        simpleTitle: '5. Pipeline Completed',
        layer: 'User Space & Terminal',
        activeNode: 'terminal',
        route: { from: 'cpu', to: 'terminal', color: 0x00f3ff },
        sound: 'success',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: 'write(1, "42\\n", 3)',
        registers: { RAX: '3', RDI: '1', RSI: '"42\\n"' },
        simpleExplanation: '`grep` reaches end of file and exits. `wc` counts the total matches (42), writes "42\\n" to your terminal, and exits. Both processes are cleaned up.',
        explanation: '`wc -l` finishes counting lines received from pipe and writes the total count to stdout.',
        analogy: '💡 Analogy: Worker B shouts the final total "42" to the manager.',
        codeSnippet: `write(1, "42\\n", 3);\nwaitpid(pid1, &s1, 0); waitpid(pid2, &s2, 0);`,
        terminalOutput: `42\nuser@linux:~$ `
      }
    ]
  },

  'mkdir my_project': {
    name: 'mkdir my_project',
    title: 'Directory Inode Allocation & Ext4 Superblock Update',
    summaryText: 'How Linux creates a folder: Allocates a new Inode on the filesystem, links parent directory, and commits to the filesystem journal.',
    stages: [
      {
        id: 'mkdir_input',
        stepNum: 1,
        timeOffset: 0,
        name: '1. mkdirat() Syscall Entry',
        simpleTitle: '1. Requesting New Folder',
        layer: 'Syscall Gateway',
        activeNode: 'syscall_dispatcher',
        route: null,
        sound: 'syscall',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'mkdirat(258)',
        registers: { RAX: '258', RDI: 'AT_FDCWD', RSI: '"my_project"', RDX: '0777 (mode)' },
        simpleExplanation: '`mkdir` calls `mkdirat()` asking the kernel to create a directory named "my_project" with permissions 0777 (adjusted by your umask to 0755).',
        explanation: 'mkdir invokes mkdirat() passing current working directory handle and permission mode mask modified by umask.',
        analogy: '💡 Analogy: Asking the warehouse manager to reserve a new empty labeled storage room.',
        codeSnippet: `sys_mkdirat(AT_FDCWD, "my_project", 0777);`,
        terminalOutput: `user@linux:~$ mkdir my_project`
      },
      {
        id: 'mkdir_inode_alloc',
        stepNum: 2,
        timeOffset: 900,
        name: '2. Filesystem Allocates New Inode',
        simpleTitle: '2. Allocating Inode on Disk',
        layer: 'VFS & Filesystem',
        activeNode: 'vfs_tree',
        route: { from: 'syscall', to: 'vfs', color: 0x00ff88 },
        sound: 'disk',
        cameraTarget: 'vfs',
        ring: 0,
        syscall: 'ext4_new_inode()',
        registers: { INODE_ID: '#105432', MODE: 'S_IFDIR | 0755', LINKS: '2' },
        simpleExplanation: 'The ext4 filesystem searches the inode bitmap for a free inode ID (e.g. #105432), sets type to Directory, and links "." and "..".',
        explanation: 'Filesystem allocates a free inode from the inode bitmap, sets directory flag (S_IFDIR), and links count to 2 (. and parent).',
        analogy: '💡 Analogy: Assigning Room #105432 and programming the electronic door key.',
        codeSnippet: `struct inode *inode = ext4_new_inode(dir, S_IFDIR | mode);\next4_add_entry(dir, dentry, inode);`,
        terminalOutput: null
      },
      {
        id: 'mkdir_journal',
        stepNum: 3,
        timeOffset: 1900,
        name: '3. Ext4 Journal Commit (Crash Safety)',
        simpleTitle: '3. Committing to Disk Journal',
        layer: 'Hardware Storage',
        activeNode: 'disk',
        route: { from: 'vfs', to: 'disk', color: 0x00ff88 },
        sound: 'disk',
        cameraTarget: 'vfs',
        ring: 0,
        syscall: 'jbd2_journal_commit_transaction()',
        registers: { TID: '9042', BLOCK_GROUP: '3' },
        simpleExplanation: 'To prevent data corruption if power cuts off, ext4 logs this change to the filesystem journal (JBD2) before confirming it on the disk superblock.',
        explanation: 'Ext4 writes the metadata transaction to the JBD2 journal to ensure crash-consistency before flushing to the superblock.',
        analogy: '💡 Analogy: Writing the transaction into the permanent ledger first so it cannot be lost.',
        codeSnippet: `jbd2_journal_start(journal, 2);\njbd2_journal_stop(handle);`,
        terminalOutput: null
      },
      {
        id: 'mkdir_done',
        stepNum: 4,
        timeOffset: 2800,
        name: '4. Folder Ready & Shell Prompt Returned',
        simpleTitle: '4. Folder Created Successfully',
        layer: 'User Space & Terminal',
        activeNode: 'terminal',
        route: { from: 'disk', to: 'terminal', color: 0x00f3ff },
        sound: 'success',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: 'exit_group(0)',
        registers: { RAX: '0' },
        simpleExplanation: 'Directory "my_project" is now live on disk and visible to all programs. Process exits cleanly with code 0.',
        explanation: 'Directory "my_project" is registered in parent directory entry table. Process returns exit code 0.',
        analogy: '💡 Analogy: The new room is unlocked and ready for files.',
        codeSnippet: `return 0;`,
        terminalOutput: `user@linux:~$ `
      }
    ]
  },

  'kill -9 1337': {
    name: 'kill -9 1337',
    title: 'Kernel Signal Delivery & Process Termination',
    summaryText: 'How process killing works: Syscall sends uncatchable SIGKILL (9) to target process. Kernel immediately frees its RAM and closes files.',
    stages: [
      {
        id: 'kill_syscall',
        stepNum: 1,
        timeOffset: 0,
        name: '1. sys_kill(1337, SIGKILL [9])',
        simpleTitle: '1. Sending SIGKILL (Signal 9)',
        layer: 'Syscall Gateway',
        activeNode: 'syscall_dispatcher',
        route: null,
        sound: 'syscall',
        cameraTarget: 'syscall',
        ring: 0,
        syscall: 'kill(62)',
        registers: { RAX: '62', RDI: '1337 (Target PID)', RSI: '9 (SIGKILL)' },
        simpleExplanation: '`kill` command asks the kernel to send signal 9 (SIGKILL) to PID 1337. Unlike SIGTERM (15), SIGKILL cannot be blocked or ignored by the program!',
        explanation: 'kill command executes sys_kill to request immediate termination of target PID 1337.',
        analogy: '💡 Analogy: An emergency power shutoff switch pulled by building security.',
        codeSnippet: `kill(1337, SIGKILL);`,
        terminalOutput: `user@linux:~$ kill -9 1337`
      },
      {
        id: 'kill_task_lookup',
        stepNum: 2,
        timeOffset: 900,
        name: '2. Kernel Finds Process in PID Table',
        simpleTitle: '2. Kernel Locates PID 1337',
        layer: 'Kernel Process Core',
        activeNode: 'cpu_core',
        route: { from: 'syscall', to: 'cpu', color: 0xff0055 },
        sound: 'kernel',
        cameraTarget: 'kernel',
        ring: 0,
        syscall: 'find_task_by_vpid()',
        registers: { TASK_PTR: '0xffff88812000', STATE: 'TASK_RUNNING' },
        simpleExplanation: 'Kernel searches its internal process hash table for PID 1337 and verifies you have permission (same user or root) to terminate it.',
        explanation: 'Kernel finds target task_struct in PID hash table and verifies EUID/UID permission to signal the process.',
        analogy: '💡 Analogy: Security guards check their personnel database to locate worker 1337.',
        codeSnippet: `struct task_struct *p = find_task_by_vpid(1337);\nsend_sig_info(SIGKILL, SEND_SIG_PRIV, p);`,
        terminalOutput: null
      },
      {
        id: 'kill_deliver',
        stepNum: 3,
        timeOffset: 1800,
        name: '3. Kernel Immediately Reclaims All RAM & Files',
        simpleTitle: '3. Memory Wiped & Descriptors Closed',
        layer: 'Kernel & MMU',
        activeNode: 'mmu_memory',
        route: { from: 'cpu', to: 'mmu', color: 0xff0055 },
        sound: 'fork',
        cameraTarget: 'kernel',
        ring: 0,
        syscall: 'do_exit(SIGKILL)',
        registers: { STATE: 'TASK_DEAD', MM: 'FREED', FD_TABLE: 'CLOSED' },
        simpleExplanation: 'The kernel immediately invokes do_exit(). It unmaps all virtual RAM pages, closes all open file handles/sockets, and marks the process state as TASK_DEAD.',
        explanation: 'SIGKILL cannot be caught or ignored. Kernel immediately invokes do_exit(), frees virtual memory pages, closes all open file descriptors, and notifies parent with SIGCHLD.',
        analogy: '💡 Analogy: Instantly clearing the desk, locking the doors, and reclaiming company badge.',
        codeSnippet: `do_exit(SIGKILL);\nexit_mm(tsk);\nexit_files(tsk);`,
        terminalOutput: null
      },
      {
        id: 'kill_prompt',
        stepNum: 4,
        timeOffset: 2700,
        name: '4. Process Reaped & Prompt Returned',
        simpleTitle: '4. Process Successfully Terminated',
        layer: 'User Space & Terminal',
        activeNode: 'terminal',
        route: { from: 'mmu', to: 'terminal', color: 0x00f3ff },
        sound: 'success',
        cameraTarget: 'userspace',
        ring: 3,
        syscall: null,
        registers: { RAX: '0' },
        simpleExplanation: 'Parent process is sent SIGCHLD to notify it of death. Terminal prints "[Killed]" notification and gives back control.',
        explanation: 'Target process 1337 terminated. Terminal returns prompt.',
        analogy: '💡 Analogy: Security reports job done. Ready for next task.',
        codeSnippet: `return 0;`,
        terminalOutput: `[1]+  Killed                  ./heavy_worker\nuser@linux:~$ `
      }
    ]
  }
};
